name: CI

on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.1.1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "v18"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - run: npm test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
